### ISSUE TITLE
Problema con id

### ISSUE THREAD

**Issue by jimmygallardo** [IIC2143/Syllabus#16]
buenas, llevo corriendo varios dias mi codigo y me sigue arrojando el mismo error:

Expected:
{
    "id": 369,
    "name": "Quentin Tarantino",
    "age": 57,
    "country": "United States",
    "has_oscars": true
}
Traceback (most recent call last):
  File "/mnt/c/Users/Jimmy/OneDrive - uc.cl/Escritorio/semestre 8/ignerieria de software/repo/2023-2-Tester-Tarea/test_1A.py", line 37, in <module>
    test_1A()
  File "/mnt/c/Users/Jimmy/OneDrive - uc.cl/Escritorio/semestre 8/ignerieria de software/repo/2023-2-Tester-Tarea/test_1A.py", line 22, in test_1A
    6: get_director(directors[0], show = True),
  File "src/part_1.py", line 56, in get_director
  File "src/models.py", line 26, in is_valid
KeyError: 'id'

Hoy hable con la profe si podia ser alguna validacion pero todas me dijo que estaban bien, salvo la de has_oscars que ya la corregi como ella me dijo, y bueno sigue el mismo error, me pasa en todos los test en los que le tengo que mandar un id, gracias

**Comment by OrregoSilva** [comment]
Hola!
Lo más probable es que el error ocurre cuando se crean los recursos, por ende no se está asignando la id, revisa bien esos otros endpoints y revisa si esos pasan. Puedes comentar las líneas de los tests si quieres comprobar hasta cierto punto con el cuidado de descomentarlas después. Si el error persiste, sube tu código para revisarlo.
Saludos!

**Comment by FranciscoOrtuzar** [comment]
Hola, tengo el mismo error y no logro solucionarlo
