### ISSUE TITLE
Error al querer crear una instancia de Match

### ISSUE THREAD

**Issue by esperanzaacevedo** [IIC2143/Syllabus#46]
Hola, si algún ayudante me puede ayudar a resolver este error que tira al intentar crear un instancia de Match,

3.1.0 :012 > ma = Match.new(teamA: e1, teamB: e2, state: true, result: "2-1")
/Users/esperanzaacevedoroman/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.8.1/lib/active_record/reflection.rb:441:in `rescue in compute_class': Rails couldn't find a valid model for TeamA association. Please provide the :class_name option on the association declaration. If :class_name is already provided, make sure it's an ActiveRecord::Base subclass. (NameError)

          raise NameError, msg
          ^^^^^
/Users/esperanzaacevedoroman/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.8.1/lib/active_record/inheritance.rb:259:in `compute_type': uninitialized constant Match::TeamA (NameError)

            raise NameError.new("uninitialized constant #{candidates.first}", candidates.first)
            ^^^^^
3.1.0 :013 > 

Quizas tengo al malo en la asociación
Dejo fotos
<img width="624" alt="Captura de pantalla 2024-03-21 a la(s) 21 05 18" src="https://github.com/IIC2143/Syllabus/assets/141953897/309d2f09-0f08-4c6b-b7ef-7dd3e6e68503">
<img width="717" alt="Captura de pantalla 2024-03-21 a la(s) 21 05 50" src="https://github.com/IIC2143/Syllabus/assets/141953897/8b987174-4429-45df-86ca-bc0549b5f439">
<img width="705" alt="Captura de pantalla 2024-03-21 a la(s) 21 10 48" src="https://github.com/IIC2143/Syllabus/assets/141953897/e8370416-f3fc-4e4c-b099-10cfda83a423">

**Comment by tomastrivino** [comment]
Nada q ver pero en tu match tus foreign key son las mismas (team_id). Quizá por ahí haya algun error?
