### ISSUE TITLE
Error al Correr Test Case

### ISSUE THREAD

**Issue by paolactrjs** [IIC2143/Syllabus#54]
Hola! Traté de probar los testase pero me sale el siguiente error: 
     
Traceback (most recent call last):
  File "backend/main.py", line 6, in <module>
    from test_1A import test_1A
  File "/Users/paolacontreras/GamersApi/Tester-Tarea-2024-2/backend/test_1A.py", line 4, in <module>
    from src.part_1 import (
  File "/Users/paolacontreras/GamersApi/Tester-Tarea-2024-2/backend/src/part_1.py", line 1, in <module>
    from requests import get, post, delete
ModuleNotFoundError: No module named 'requests'

Instalé el módulo que me decía, y aun así me sigue saliendo ese error.

**Comment by waknaudt** [comment]
Puede ser problema de tu environment, si lo estas corriendo de la terminal escribe `python` o el comando que ocupes para ejecutar python y luego en la consola interactiva de python escribe `import requests`, si te tira error es que la el modulo requests no se esta instalando en el python que ejecutas por consola si no en "otro" python. En ese caso puedes escribir en consola `where python` para ver si tienes mas de un python instalado

**Comment by jtvaldivia** [comment]
Como dijo tu compañero, puede que lo hayas instalado en otra version de python que no es la que estas tratando de ejecutar
